[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.126.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.126.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.126.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.126.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# Redirects
[[redirects]]
  from = "/playpen/*"
  to = "/:splat"
  
[[redirects]]
  from = "/power-of-ten/*"
  to = "/podcasts/"
  
[[redirects]]
  from = "/coaching/*"
  to = "/teaching/coaching/design-leadership-coaching/"

[[redirects]]
  from = "/npmjs/*"
  to = "/npmjs/"
  status = 200
  
[[redirects]]
  from = "/mt/*"
  to = "/:splat"

[[redirects]]
  from = "/feed"
  to = "/index.xml"
  status = 200
  force = true

[[redirects]]
  from = "/feed/"
  to = "/index.xml"
  status = 200
  force = true